### ISSUE TITLE
Add Simplified Testing Setup Using Configuration File

### ISSUE THREAD

**Issue by jrg94** [auroq/glotter#2]
## Is your feature request related to a problem? Please describe.

We talked about this in the past, but we shouldn't have to edit three different files
every time we wanted to add a new project. Specifically, it would be awesome if
there was a way to add testing directly into the .glotter.yml file. Then, the runner.py
and individual pytest files could be generated dynamically. 

## Describe the solution you'd like

See above!

### Describe how this would look for clients integrating with Glotter (if applicable).

```yml
projects:
    removeallwhitespace:
        words:
            - "bubble"
            - "sort"
        requires_parameters: true
        tests:
            valid:
                - nospaces:
                    input: "RemoveAllSpaces"
                    output: "RemoveAllSpaces"
            invalid:
                - noinput:
                    input: ""
                    output: "Usage: please provide a string" 
```

This would probably be very quickly overwhelming, so maybe a folder like tests where there is
one of these for each project? In other words, keep the glotter config as-is, but repurpose the tests
directory to contain only YAML files.
